# Generated by Django 3.2 on 2021-05-03 05:30

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_time', models.CharField(max_length=200)),
                ('teacher_tel', models.CharField(max_length=20)),
                ('teacher_mailbox', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('introduction', ckeditor.fields.RichTextField()),
                ('tel', models.CharField(max_length=20)),
                ('mailbox', models.CharField(max_length=200)),
                ('class_time', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='Start Date')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('Start_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.teacher')),
            ],
            options={
                'verbose_name': 'Course_name',
                'verbose_name_plural': 'Course_name',
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('experiment_No', models.IntegerField(default=0, verbose_name='第几次实验')),
                ('info', models.CharField(blank=True, max_length=500, verbose_name='该次实验描述')),
                ('class_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.classtime')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('techer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.teacher')),
            ],
            options={
                'verbose_name': '一次实验课',
                'verbose_name_plural': '一次实验课',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='姓名')),
                ('studentid', models.CharField(max_length=10, verbose_name='学生证号')),
                ('tel', models.CharField(max_length=20)),
                ('mailbox', models.CharField(max_length=200)),
                ('perm', models.IntegerField(default=0, verbose_name='权限')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
            },
        ),
        migrations.CreateModel(
            name='techer_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lesson_No', models.IntegerField(default=0, verbose_name='第几次课')),
                ('date', models.DateTimeField(verbose_name='上课日期')),
                ('note', models.CharField(max_length=200, verbose_name='该次实验反映问题与教师记录')),
                ('class_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.classtime')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='studentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lesson_No', models.IntegerField(default=0, verbose_name='第几次课')),
                ('student_name', models.CharField(max_length=20)),
                ('student_id', models.CharField(max_length=20)),
                ('Experiment_completion', models.CharField(max_length=200, verbose_name='学生i的实验完成情况')),
                ('date', models.DateTimeField(verbose_name='上课日期')),
                ('note', models.CharField(max_length=200, verbose_name='该次实验反映问题与改进建议')),
                ('class_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.classtime')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('techer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Experimentpart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=600)),
                ('votes', models.IntegerField(default=0)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.experiment')),
            ],
        ),
        migrations.AddField(
            model_name='classtime',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
        migrations.AddField(
            model_name='classtime',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.student'),
        ),
        migrations.AddField(
            model_name='classtime',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.teacher'),
        ),
    ]
