# Generated by Django 3.2 on 2021-05-07 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classtime',
            name='student',
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('classtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.classtime')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.student')),
            ],
        ),
        migrations.AddField(
            model_name='classtime',
            name='students',
            field=models.ManyToManyField(through='course.Membership', to='course.Student'),
        ),
    ]
